version: '3.8'
services:

##########################################################################
#  CORE SERVICES
##########################################################################
  nginx:
    container_name: nginx
    image: ${NGINX}
    restart: unless-stopped
    networks:
      - simplilearn
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/:/etc/nginx/:ro

##########################################################################
#  CI/CD Application(s) and Service(s)
##########################################################################
  jenkins:
    container_name: jenkins
    image: ${JENKINS}
    restart: unless-stopped
    networks:
      - simplilearn
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
    volumes:
      - jenkins_data:/var/jenkins_home:z
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

##########################################################################
#  Project Application(s) and Service(s)
##########################################################################
  inventory-management:
    container_name: inventory-management
    image: ${INVENTORY_MANAGER}
    restart: unless-stopped
    networks:
      - simplilearn
    ports:
      - "3000:3000"
    environment:
      PREFIX: '/inventory-management'
      SWAGGER_SERVER_URL: 'https://localhost/inventory-management'


volumes:
  jenkins_data:

networks:
  simplilearn:
    driver: bridge